
set nocompatible
filetype off

" alternatively, pass a path where Vundle should install plugins

" let Vundle manage Vundle, required
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'plasticboy/vim-markdown'
Plug 'vim-airline/vim-airline'
Plug 'vhdirk/vim-cmake'
Plug 'cespare/vim-toml'
Plug 'julialang/julia-vim'
Plug 'knubie/vim-kitty-navigator', {'do': 'cp ./*.py ~/.config/kitty/'}
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'czheo/mojo.vim'
" Plug 'quarto-dev/quarto-vim'
Plug 'lahvak/quarto-vim', {'branch': 'julia_highlight'}
call plug#end()

filetype plugin indent on

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4

nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>

set noswapfile
set autoread
set hidden
set title
filetype plugin indent on

if has('nvim')
    set termguicolors
    let g:airline#extensions#tabline#enabled = 1
    let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
    nnoremap <F19> <Cmd>bprev<CR>
    nnoremap <F20> <Cmd>bnext<CR>
    nnoremap <Leader>q <Cmd>bdelete<CR>
endif

